### ISSUE TITLE
avahi to reflect mDNS between docker internal LAN and outside real-world networking

### ISSUE THREAD

**Issue by keiranharris** [flungo-docker/avahi#2]
Hi, love the idea of your container (so thank you!)- i thought you solved my problem. You probably still can but im stumbling on the setup to the outside world. 

Your README.md spells out how to connect avahi container between two *internal* docker networks (net1 to net2 in your example)..... but I need to go from an internal docker LAN (named 'kTier2_PROXYtoAPP' in my case - which is 172.20.2.0/24) to the outside world (in my case, the NIC of the ubuntu host, on 10.1.3.0/24), which is where the mDNS announce packets are coming from.  

after booting your container (attaching to --network kTier2_PROXYtoAPP), I tried 'docker network connect' to 
- 'host' (wasn't allowed) and 
- 'bridge' (allowed, but connected me to docker0 LAN - 172.12.0.0/24 - which is unused for me) 
but neither worked. 

any ideas? Im a bit of a noob to docker networking (im a real world networking expert though if that helps!).
thanks, 
Keiran.

**Comment by flungo** [comment]
Hey, thanks for your interest in this repository. I have been using this for a few years now to connect between multiple physical networks. I have been using the [macvlan](https://docs.docker.com/network/macvlan/) network driver. I think something like this should do the trick for you (assuming `eno1` is the interface name on your host, `10.1.3.1` is your gateway and `10.1.3.10` is an available IP on your network):

```bash
# Start the container in your kTier2_PROXYtoAPP network
docker run -d --name=mdns-reflector \
  --network kTier2_PROXYtoAPP \
  -e REFLECTOR_ENABLE_REFLECTOR=yes \
  flungo/avahi
# Create the docker network (named lan) using the macvlan driver
docker network create --driver macvlan --subnet 10.1.3.0/24 --gateway 10.1.3.1 --opt parent=eno1 lan
# Connect the container to the lan network with the IP 10.1.3.10
docker network connect lan mdns-reflector --ip 10.1.3.10
```

I have not tried this with connecting to the native VLAN of the host interface so can only vouch for this working where the parent has the VLAN ID suffixed (e.g. `eno1.123` for VLAN 123). Please let me know how you get on with the above.

I'll update the README with some detail on setting this up as I suspect this will be the most common use case for most people who might want to use this container.

**Comment by keiranharris** [comment]
amazing ! it worked, first go, you sir are a legend. Thanks again. 
![20210118_18-22-54_keharris — keiran@vm-untrust: ~ — ssh keiran@vm-untrust — 137×43](https://user-images.githubusercontent.com/22670742/104884506-94ca3100-59ba-11eb-85e1-896e76533b3b.jpg)

**Comment by keiranharris** [comment]
and, oh, if you wanted it in docker-compose form, I've just validated, this works: 
![20210118_19-06-58_docker-compose yaml — _K (Workspace)](https://user-images.githubusercontent.com/22670742/104888126-68b1ae80-59c0-11eb-8255-d8eb751e0418.jpg)

**Comment by Chuckame** [comment]
Hey @keiranharris and @flungo 
I absolutely cannot make it works like you...

btw, @keiranharris how to display all mdns entries in home assistant like you ?

Here my compose file:
```yaml
version: "3.7"

networks:
  traefik:
    name: ${TRAEFIK_NETWORK_NAME}
  mqtt:
  mdns-discovering:
    driver: bridge
    name: mdns-discovering
    ipam:
      config:
        - subnet: 172.66.1.0/24
  lan:
    name: lan
    driver: macvlan
    driver_opts:
      parent: ${LAN_NETWORK_DEVICE}
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  config:
  esphome_config:

services:
  homeassistant:
    image: homeassistant/home-assistant:2021.12.9
    environment:
      TZ: ${TZ}
    depends_on:
      - mqtt-server
      - esphome
      - mdns-repeater
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - traefik
      - mdns-discovering
    labels:
      - "traefik.enable=true"
      - ... traefik labels

  mdns-repeater:
    build: ./mdns-repeater
    restart: unless-stopped
    environment:
      REFLECTOR_ENABLE_REFLECTOR: "yes"
    networks:
      lan:
        ipv4_address: 192.168.1.101
      mdns-discovering:

... other services
```

> The content of `./mdns-repeater` is the same as this repository, since the docker has no build for armv7

Output of avahi image logs:
```
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Successfully called chroot().
Successfully dropped remaining capabilities.
Loading service file /services/sftp-ssh.service.
Loading service file /services/ssh.service.
Joining mDNS multicast group on interface eth1.IPv4 with address 172.66.1.2.
New relevant interface eth1.IPv4 for mDNS.
Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.1.101.
New relevant interface eth0.IPv4 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for 172.66.1.2 on eth1.IPv4.
Registering new address record for 192.168.1.101 on eth0.IPv4.
Registering new address record for 127.0.0.1 on lo.IPv4.
Server startup complete. Host name is 78a50c516b07.local. Local service cookie is 1689271438.
Service "78a50c516b07" (/services/ssh.service) successfully established.
Service "78a50c516b07" (/services/sftp-ssh.service) successfully established.
```

**Comment by keiranharris** [comment]
Looking at your compose i think you have it around the wrong way. The avahi container should be across two networks, and hass only across one. The idea here is that avahi (by way of the macvlan driver) is repeating mDNS broadcast into docker networking from the outside real world - hence it needs a leg on both outside (macvlan) and inside docker (bridge) where you hass sits.

**Comment by miamilabs** [comment]
> Hi, love the idea of your container (so thank you!)- i thought you solved my problem. You probably still can but im stumbling on the setup to the outside world.
> 
> Your README.md spells out how to connect avahi container between two _internal_ docker networks (net1 to net2 in your example)..... but I need to go from an internal docker LAN (named 'kTier2_PROXYtoAPP' in my case - which is 172.20.2.0/24) to the outside world (in my case, the NIC of the ubuntu host, on 10.1.3.0/24), which is where the mDNS announce packets are coming from.
> 
> after booting your container (attaching to --network kTier2_PROXYtoAPP), I tried 'docker network connect' to
> 
>     * 'host' (wasn't allowed) and
> 
>     * 'bridge' (allowed, but connected me to docker0 LAN - 172.12.0.0/24 - which is unused for me)
>       but neither worked.
> 
> 
> any ideas? Im a bit of a noob to docker networking (im a real world networking expert though if that helps!). thanks, Keiran.

This one is pretty old and i am running in same issue as you.
I have homeassistant installed in docker on OSx (M1) and host mode is not allowed. But it looks like macvlan is not working as well on osx .

Did you run this in Apple machine?

**Comment by keiranharris** [comment]
> Did you run this in Apple machine?

Nah - ubuntu.

**Comment by AndreasBVB** [comment]
Hi guys, I'm setting up like this:
sudo docker network create --driver macvlan --subnet=10.10.10.0/24 --opt parent=wlp1s0 mdnsvlan
sudo docker create \
--name=avahi \
--net mdnsvlan \
--ip 10.10.10.9 \
-e REFLECTOR_ENABLE_REFLECTOR=yes \
--restart=always \
flungo/avahi

inspecting mdnsvlan seems all normal:
    {
        "Name": "mdnsvlan",
        "Id": "9d6b5a717d57737cddcc42dc40d273b07ee4f0007225f6cf66c13672970e4508",
        "Created": "2023-10-19T14:13:40.499332444-04:00",
        "Scope": "local",
        "Driver": "macvlan",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "10.10.10.0/24"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "ad7348f9fdb2d5ce359f79cdd2938b97239c5d1add6f1f6a7854dc7626264e3b": {
                "Name": "avahi",
                "EndpointID": "360bb36475388b2c67207c4bc481d7e7816dba336e72f215111b657c4d5107e7",
                "MacAddress": "02:42:0a:0c:13:09",
                "IPv4Address": "10.10.10.9/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "parent": "wlp1s0"
        },
        "Labels": {}
    }

Avahi container log:
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Successfully called chroot().
Successfully dropped remaining capabilities.
Loading service file /services/sftp-ssh.service.
Loading service file /services/ssh.service.
Joining mDNS multicast group on interface eth0.IPv4 with address 10.10.10.9.
New relevant interface eth0.IPv4 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for 10.10.10.9 on eth0.IPv4.
Registering new address record for 127.0.0.1 on lo.IPv4.
Server startup complete. Host name is ad7348f9fdb2.local. Local service cookie is 263389164.
Service "ad7348f9fdb2" (/services/ssh.service) successfully established.
Service "ad7348f9fdb2" (/services/sftp-ssh.service) successfully established.

However on my router (ASUS-AC86U Merlin) log I see endless messages like this:
Oct 19 13:14:52 wlceventd: WLCEVENTD wlceventd_proc_event(466): eth6: Deauth_ind 02:42:0A:0C:13:09, status: 0, reason: Class 3 frame received from nonassociated station (7)

Any recommendations? Thanks a lot!

**Comment by flungo** [comment]
The problem you are experiencing is due to using the macvlan driver on a WiFi device. Wireless routers will only expect to see MAC addresses from clients they have associated with (e.g. your laptop or raspberry pi), however the macvlan driver will forward packets from the container which has its own MAC addresses which your AP does not recognise.

Are you able to connect the device which you want to run the mdns reflector on to your AP via an ethernet cable? That will be the easiest and most reliable solution to this.

You could try ipvlan (see [Macvlan vs Ipvlan](https://hicu.be/macvlan-vs-ipvlan) which also describes this problem and the [ipvlan docs](https://docs.docker.com/network/drivers/ipvlan/)) however I am not sure if avahi will function correctly on your network when using this driver as I have not tested.

**Comment by AndreasBVB** [comment]
> The problem you are experiencing is due to using the macvlan driver on a WiFi device. Wireless routers will only expect to see MAC addresses from clients they have associated with (e.g. your laptop or raspberry pi), however the macvlan driver will forward packets from the container which has its own MAC addresses which your AP does not recognise.
> 
> Are you able to connect the device which you want to run the mdns reflector on to your AP via an ethernet cable? That will be the easiest and most reliable solution to this.
> 
> You could try ipvlan (see [Macvlan vs Ipvlan](https://hicu.be/macvlan-vs-ipvlan) which also describes this problem and the [ipvlan docs](https://docs.docker.com/network/drivers/ipvlan/)) however I am not sure if avahi will function correctly on your network when using this driver as I have not tested.

RJ45 cable did the trick. Would have taken me forever to figure out. Thank you so much!

**Comment by nabheet** [comment]
should/will this work in a docker swarm set up also?

**Comment by nabheet** [comment]
I feel like I am so close!!!

```
nabheet@potter:~$ docker logs -f 6e92e1302497
Saved 1 file(s)
Saved 1 file(s)
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Successfully called chroot().
Successfully dropped remaining capabilities.
Loading service file /services/sftp-ssh.service.
Loading service file /services/ssh.service.
Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.86.8.
New relevant interface eth0.IPv4 for mDNS.
Joining mDNS multicast group on interface eth1.IPv4 with address 10.0.7.236.
New relevant interface eth1.IPv4 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for 192.168.86.8 on eth0.IPv4.
Registering new address record for 10.0.7.236 on eth1.IPv4.
Registering new address record for 127.0.0.1 on lo.IPv4.
Server startup complete. Host name is 6e92e1302497.local. Local service cookie is 3074494474.
Service "6e92e1302497" (/services/ssh.service) successfully established.
Service "6e92e1302497" (/services/sftp-ssh.service) successfully established.
```

My ESPHome container and Home-Assistant are not seeing any of the .local names which they used to when connected to the host network.

I am not sure what I am missing. I can ping the internet and ping each of the containers. so I think networking is mostly working.

```
nabheet@potter:~$ docker exec -it 6e92e1302497 ash
/ # ip add
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
737: eth1@if738: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 02:42:0a:00:07:ec brd ff:ff:ff:ff:ff:ff
    inet 10.0.7.236/24 brd 10.0.7.255 scope global eth1
       valid_lft forever preferred_lft forever
741: eth0@if4: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:c0:a8:56:08 brd ff:ff:ff:ff:ff:ff
    inet 192.168.86.8/24 brd 192.168.86.255 scope global eth0
       valid_lft forever preferred_lft forever
/ # ip route
default via 192.168.86.1 dev eth0 
10.0.7.0/24 dev eth1 scope link  src 10.0.7.236 
192.168.86.0/24 dev eth0 scope link  src 192.168.86.8 
/ # 
```

**Comment by miamilabs** [comment]
> I feel like I am so close!!!
> 
> ```
> nabheet@potter:~$ docker logs -f 6e92e1302497
> Saved 1 file(s)
> Saved 1 file(s)
> Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
> Successfully dropped root privileges.
> avahi-daemon 0.8 starting up.
> WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
> Successfully called chroot().
> Successfully dropped remaining capabilities.
> Loading service file /services/sftp-ssh.service.
> Loading service file /services/ssh.service.
> Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.86.8.
> New relevant interface eth0.IPv4 for mDNS.
> Joining mDNS multicast group on interface eth1.IPv4 with address 10.0.7.236.
> New relevant interface eth1.IPv4 for mDNS.
> Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
> New relevant interface lo.IPv4 for mDNS.
> Network interface enumeration completed.
> Registering new address record for 192.168.86.8 on eth0.IPv4.
> Registering new address record for 10.0.7.236 on eth1.IPv4.
> Registering new address record for 127.0.0.1 on lo.IPv4.
> Server startup complete. Host name is 6e92e1302497.local. Local service cookie is 3074494474.
> Service "6e92e1302497" (/services/ssh.service) successfully established.
> Service "6e92e1302497" (/services/sftp-ssh.service) successfully established.
> ```
> 
> My ESPHome container and Home-Assistant are not seeing any of the .local names which they used to when connected to the host network.
> 
> I am not sure what I am missing. I can not ping the internet and ping each of the containers. so I think networking is mostly working.
> 
> ```
> nabheet@potter:~$ docker exec -it 6e92e1302497 ash
> / # ip add
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
> 737: eth1@if738: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
>     link/ether 02:42:0a:00:07:ec brd ff:ff:ff:ff:ff:ff
>     inet 10.0.7.236/24 brd 10.0.7.255 scope global eth1
>        valid_lft forever preferred_lft forever
> 741: eth0@if4: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
>     link/ether 02:42:c0:a8:56:08 brd ff:ff:ff:ff:ff:ff
>     inet 192.168.86.8/24 brd 192.168.86.255 scope global eth0
>        valid_lft forever preferred_lft forever
> / # ip route
> default via 192.168.86.1 dev eth0 
> 10.0.7.0/24 dev eth1 scope link  src 10.0.7.236 
> 192.168.86.0/24 dev eth0 scope link  src 192.168.86.8 
> / # 
> ```

Is there any way you can share the config?

I am on travel now but I would like to dig into it as well so I can remove my raspberry’s

**Comment by nabheet** [comment]
Funny story, I had to move my esphome container to the same box as the avahi daemon and now it is can resolve the names. I don't know if it is because the previous workstation is on Wifi or that the two containers were on different nodes but things seem to be working from ESPHome's perspective. Whereas HomeAssistant Apple Home Bridge is still not working ... :shrug: 

Here you go:

```
  ha:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ha_config:/config
      - ha_media:/media
      - ha_local:/.local
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123
      - 1900:1900
      - 1901:1901
      - 5353:5353
      - 5683:5683
      - 51827:51827
      - 21064:21064
      - 21063:21063
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8123/"]
      interval: 30s
      timeout: 1s
      retries: 10
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.webproxy == true

  eh:
    image: ghcr.io/esphome/esphome:stable
    volumes:
      - esphome_config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
     - 6052:6052
     - 6053:6053
     - 6123:6123
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:6052/"]
      interval: 30s
      timeout: 1s
      retries: 10
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.webproxy == true

  a:
    image: flungo/avahi
    environment:
      - REFLECTOR_ENABLE_REFLECTOR=yes
    networks:
      lan: {}
      default: {}
    # healthcheck:
    #   test: ["CMD", "curl", "-sI", "http://127.0.0.1:3000/"]
    #   interval: 30s
    #   timeout: 1s
    #   retries: 10
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.webproxy == true

```

BTW, all of my volumes are NFS volume mounts using the docker NFS driver. And I removed Lets Encrypt specific settings too.
